version: '3.4'

services:
  netcoretcpprobes:
    image: ${DOCKER_REGISTRY-}mikesigs/tcp-health-checks-example
    ports:
      - "13000:13000"
      - "13001:13001"
    build:
      context: .
      dockerfile: Example/Dockerfile
