version: '3.4'

services:
  simpleexamplewithdefaults:
    image: ${DOCKER_REGISTRY-}simpleexamplewithdefaultscustomhealthchecksexample
    ports: 
    - "13000:13000"
    - "13001:13001"
    build:
      context: .
      dockerfile: samples/SimpleExampleWithDefaults/Dockerfile

  customhealthchecksexample:
    image: ${DOCKER_REGISTRY-}customhealthchecksexample
    ports: 
    - "13002:13002"
    - "13003:13003"
    build:
      context: .
      dockerfile: samples/CustomHealthChecksExample/Dockerfile

